app_offers_api:
    resource: "@AppBundle/Controller/OffersRESTController.php"
    type:   rest
    prefix:   /api

app_campaigns_api:
    resource: "@AppBundle/Controller/CampaignsRESTController.php"
    type:   rest
    prefix:   /api

app_companies_api:
    resource: "@AppBundle/Controller/CompaniesRESTController.php"
    type:   rest
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
