AppBundle\Entity\Profiles:
    type: entity
    table: profiles
    id:
        profId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: prof_id
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: last_name
        phone:
            type: bigint
            nullable: false
            options:
                unsigned: false
        image:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
        pdf:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
