AppBundle\Entity\RolePermission:
    type: entity
    table: role_permission
    indexes:
        role_id:
            columns:
                - role_id
        permission_id:
            columns:
                - permission_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: role_id
            orphanRemoval: false
        permission:
            targetEntity: Permission
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                permission_id:
                    referencedColumnName: permission_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
