AppBundle\Entity\TypeProduct:
    type: entity
    table: type_product
    id:
        typeId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: type_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
